setwd('C:\\Users\\jiwon.DESKTOP-J6K6P2J\\Desktop\\스무슬리')
BR_NUM_INFO = read.csv('BR_NUM_INFO.csv')
View(BR_NUM_INFO)

library(sqldf)
BR_NUM_INFO_ONEHOT = sqldf('SELECT A.PK_ITEM, A.OLD_KEY, A.CATEGORY, A.LOWER_LEN, A.INNER_LEN, A.OUTER_LEN, A.HEIGHT, A.LOWER_CUP_WIDTH, A.LOWER_CUP_LEN, A.LOWER_CUP_INNER_CURVATURE, A.LOWER_CUP_OUTER_CURVATURE, 
B.SHAPE_CUP_75, B.SHAPE_CUP_50, B.WIRE_NONEXIST, B.EXISTENCE_PP_T
                           FROM BR_NUM_INFO A
                           JOIN BR_FEATURE_ONEHOT B
                           ON A.PK_ITEM = B.PK_ITEM AND A.OLD_KEY = B.OLD_KEY')

head(BR_FEATURE_ONEHOT)
head(BR_NUM_INFO)
View(BR_NUM_INFO_ONEHOT)

write.csv(BR_NUM_INFO_ONEHOT, 'BR_NUM_INFO_ONEHOT.csv', row.names = F)
